/* The following code was generated by JFlex 1.4.3 on 4/9/13 10:31 PM */

/* Joshua Burkhart */
/* 4/11/2013 */
/* Dr. Young */
/* CIS 561 */

/* Jflex lexer specification for Cool 2013 */

import beaver.Symbol;
import beaver.Scanner;
import cool.Terminals;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/9/13 10:31 PM from the specification file
 * <tt>lexer_spec.jflex</tt>
 */
class Lexer4Cool extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 6;
  public static final int YYINITIAL = 0;
  public static final int C_STYLE_COMMENT = 8;
  public static final int OTHER_STRING = 4;
  public static final int SIMPLE_STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\57\7\0\1\57\1\60\1\17\1\0\1\60\1\16\22\0\1\20"+
    "\1\44\1\54\5\0\1\34\1\45\1\41\1\43\1\51\1\36\1\53"+
    "\1\42\1\1\11\2\1\46\1\50\1\37\1\40\1\52\2\0\32\5"+
    "\1\0\1\55\2\0\1\4\1\0\1\13\1\56\1\30\1\31\1\11"+
    "\1\12\1\3\1\24\1\25\2\3\1\14\1\32\1\21\1\27\1\22"+
    "\1\3\1\7\1\15\1\6\1\10\1\26\1\23\1\33\2\3\1\35"+
    "\1\0\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\1\3\1\4\4\3\2\5\10\3"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\2\26\2\31\1\5\13\3\1\32"+
    "\6\3\1\33\1\34\1\35\1\36\1\37\1\0\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\0\7\3"+
    "\1\47\1\3\1\16\1\3\1\50\3\3\1\51\1\3"+
    "\1\52\1\53\1\54\1\55\2\3\1\56\3\3\1\57"+
    "\3\3\1\60\1\3\1\61\1\3\1\62\1\63\1\3"+
    "\1\64\1\3\1\65\1\3\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\365"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405"+
    "\0\365\0\365\0\365\0\u0436\0\u0467\0\365\0\u0498\0\365"+
    "\0\365\0\365\0\365\0\365\0\365\0\365\0\365\0\u04c9"+
    "\0\u04fa\0\365\0\u052b\0\365\0\u055c\0\u058d\0\365\0\u05be"+
    "\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\u0157\0\u080a\0\u083b\0\u086c\0\u089d"+
    "\0\u08ce\0\u08ff\0\365\0\365\0\365\0\365\0\365\0\u0930"+
    "\0\365\0\365\0\365\0\365\0\365\0\365\0\365\0\u0961"+
    "\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0157"+
    "\0\u0ae9\0\u0157\0\u0b1a\0\u0157\0\u0b4b\0\u0b7c\0\u0bad\0\u0157"+
    "\0\u0bde\0\365\0\u0157\0\u0157\0\u0157\0\u0c0f\0\u0c40\0\u0157"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0157\0\u0d04\0\u0d35\0\u0d66\0\u0157"+
    "\0\u0d97\0\u0157\0\u0dc8\0\u0157\0\u0157\0\u0df9\0\u0157\0\u0e2a"+
    "\0\u0157\0\u0e5b\0\u0157";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\6\1\12\1\13\2\11"+
    "\1\14\1\15\2\11\1\16\1\17\2\20\1\21\1\11"+
    "\1\22\1\11\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\11\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\6"+
    "\1\47\1\50\1\6\1\11\1\6\1\20\16\51\2\6"+
    "\34\51\1\52\1\53\1\51\2\6\54\54\1\55\1\53"+
    "\3\54\16\20\1\56\1\57\102\20\1\60\17\20\62\0"+
    "\2\10\57\0\15\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\15\12\3\0\13\12\2\0\1\12\17\0"+
    "\1\12\3\0\6\11\1\61\6\11\3\0\3\11\1\62"+
    "\7\11\2\0\1\11\17\0\1\11\3\0\13\11\1\63"+
    "\1\11\3\0\12\11\1\64\2\0\1\11\17\0\1\11"+
    "\3\0\12\11\1\65\2\11\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\3\0\7\11\1\66\5\11\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\21\0\1\20\42\0\7\11"+
    "\1\67\1\70\1\11\1\71\2\11\3\0\6\11\1\72"+
    "\4\11\2\0\1\11\17\0\1\11\3\0\15\11\3\0"+
    "\3\11\1\73\7\11\2\0\1\11\17\0\1\11\3\0"+
    "\11\11\1\74\3\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\12\11\1\75\2\11\3\0\13\11\2\0"+
    "\1\11\17\0\1\11\3\0\15\11\3\0\5\11\1\76"+
    "\5\11\2\0\1\11\17\0\1\11\3\0\12\11\1\77"+
    "\1\100\1\11\3\0\13\11\2\0\1\11\17\0\1\11"+
    "\3\0\10\11\1\101\4\11\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\3\0\12\11\1\102\2\11\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\42\0\1\103\60\0\1\104"+
    "\11\0\1\105\47\0\1\106\1\107\72\0\1\110\4\0"+
    "\16\51\2\0\34\51\2\0\1\51\3\0\1\111\4\0"+
    "\1\112\1\113\2\0\1\114\6\0\1\115\32\0\1\116"+
    "\1\0\1\117\56\0\1\120\23\0\1\57\103\0\1\57"+
    "\17\0\7\11\1\121\5\11\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\3\0\15\11\3\0\4\11\1\122\6\11"+
    "\2\0\1\11\17\0\1\11\3\0\14\11\1\123\3\0"+
    "\13\11\2\0\1\11\17\0\1\11\3\0\5\11\1\124"+
    "\7\11\3\0\13\11\2\0\1\11\17\0\1\11\3\0"+
    "\13\11\1\125\1\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\15\11\3\0\1\11\1\126\11\11\2\0"+
    "\1\11\17\0\1\11\3\0\13\11\1\127\1\11\3\0"+
    "\13\11\2\0\1\11\17\0\1\11\3\0\15\11\3\0"+
    "\2\11\1\130\10\11\2\0\1\11\17\0\1\11\3\0"+
    "\5\11\1\131\7\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\5\11\1\132\7\11\3\0\13\11\2\0"+
    "\1\11\17\0\1\11\3\0\15\11\3\0\4\11\1\133"+
    "\6\11\2\0\1\11\17\0\1\11\3\0\6\11\1\134"+
    "\6\11\3\0\13\11\2\0\1\11\17\0\1\11\3\0"+
    "\10\11\1\135\4\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\14\11\1\136\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\3\0\12\11\1\137\2\11\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\3\0\11\11\1\140\3\11"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\5\11"+
    "\1\141\7\11\3\0\13\11\2\0\1\11\17\0\1\11"+
    "\56\0\1\142\60\0\1\52\5\0\10\11\1\143\4\11"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\14\11"+
    "\1\144\3\0\13\11\2\0\1\11\17\0\1\11\3\0"+
    "\10\11\1\145\4\11\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\10\11\1\146\4\11\3\0\13\11\2\0"+
    "\1\11\17\0\1\11\3\0\14\11\1\121\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\3\0\10\11\1\147\4\11"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\13\11"+
    "\1\150\1\11\3\0\13\11\2\0\1\11\17\0\1\11"+
    "\3\0\15\11\3\0\4\11\1\151\6\11\2\0\1\11"+
    "\17\0\1\11\3\0\13\11\1\152\1\11\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\3\0\6\11\1\153\6\11"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\10\11"+
    "\1\154\4\11\3\0\13\11\2\0\1\11\17\0\1\11"+
    "\3\0\14\11\1\155\3\0\13\11\2\0\1\11\17\0"+
    "\1\11\3\0\15\11\3\0\7\11\1\156\3\11\2\0"+
    "\1\11\17\0\1\11\3\0\15\11\3\0\1\157\12\11"+
    "\2\0\1\11\17\0\1\11\3\0\6\11\1\160\6\11"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\15\11"+
    "\3\0\5\11\1\161\5\11\2\0\1\11\17\0\1\11"+
    "\3\0\10\11\1\162\4\11\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\3\0\6\11\1\163\6\11\3\0\13\11"+
    "\2\0\1\11\17\0\1\11\3\0\14\11\1\164\3\0"+
    "\13\11\2\0\1\11\17\0\1\11\3\0\15\11\3\0"+
    "\3\11\1\165\7\11\2\0\1\11\17\0\1\11\3\0"+
    "\15\11\3\0\10\11\1\166\2\11\2\0\1\11\17\0"+
    "\1\11\3\0\10\11\1\167\4\11\3\0\13\11\2\0"+
    "\1\11\17\0\1\11\3\0\15\11\3\0\4\11\1\170"+
    "\6\11\2\0\1\11\17\0\1\11\3\0\14\11\1\171"+
    "\3\0\13\11\2\0\1\11\17\0\1\11\3\0\15\11"+
    "\3\0\10\11\1\172\2\11\2\0\1\11\17\0\1\11"+
    "\3\0\10\11\1\173\4\11\3\0\13\11\2\0\1\11"+
    "\17\0\1\11\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3724];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\10\1\1\11\10\1\3\11\2\1\1\11"+
    "\1\1\10\11\2\1\1\11\1\1\1\11\2\1\1\11"+
    "\23\1\5\11\1\0\7\11\1\0\21\1\1\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private int token_line;
    private int token_column;
    private String matched_text;
    private StringBuffer string = new StringBuffer();
    
    private Symbol newSymbol(short id)
    {
        return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), yytext());
    }

    private Symbol newSymbol(short id, Object value)
    {
        return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer4Cool(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer4Cool(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { /* do nothing */
          }
        case 55: break;
        case 21: 
          { string.setLength(0); yybegin(SIMPLE_STRING);
          }
        case 56: break;
        case 49: 
          { return newSymbol(Terminals.WHILE,yytext());
          }
        case 57: break;
        case 41: 
          { return newSymbol(Terminals.DEF,yytext());
          }
        case 58: break;
        case 18: 
          { return newSymbol(Terminals.SEMI,yytext());
          }
        case 59: break;
        case 33: 
          { string.append('\t');
          }
        case 60: break;
        case 23: 
          { yybegin(YYINITIAL); return newSymbol(Terminals.STRING,string.toString());
          }
        case 61: break;
        case 32: 
          { string.append('\0');
          }
        case 62: break;
        case 15: 
          { return newSymbol(Terminals.RPAREN,yytext());
          }
        case 63: break;
        case 16: 
          { return newSymbol(Terminals.COLON,yytext());
          }
        case 64: break;
        case 4: 
          { return newSymbol(Terminals.TYPE,yytext());
          }
        case 65: break;
        case 24: 
          { string.append('\\');
          }
        case 66: break;
        case 11: 
          { return newSymbol(Terminals.TIMES,yytext());
          }
        case 67: break;
        case 30: 
          { yybegin(C_STYLE_COMMENT);
          }
        case 68: break;
        case 34: 
          { string.append('\r');
          }
        case 69: break;
        case 48: 
          { return newSymbol(Terminals.SUPER,yytext());
          }
        case 70: break;
        case 25: 
          { yybegin(YYINITIAL);
          }
        case 71: break;
        case 13: 
          { return newSymbol(Terminals.PLUS,yytext());
          }
        case 72: break;
        case 31: 
          { yybegin(EOL_COMMENT);
          }
        case 73: break;
        case 28: 
          { return newSymbol(Terminals.EQUALS,yytext());
          }
        case 74: break;
        case 29: 
          { return newSymbol(Terminals.ARROW,yytext());
          }
        case 75: break;
        case 27: 
          { return newSymbol(Terminals.LE,yytext());
          }
        case 76: break;
        case 35: 
          { string.append('\f');
          }
        case 77: break;
        case 47: 
          { return newSymbol(Terminals.CASE,yytext());
          }
        case 78: break;
        case 51: 
          { return newSymbol(Terminals.MATCH,yytext());
          }
        case 79: break;
        case 9: 
          { return newSymbol(Terminals.LT,yytext());
          }
        case 80: break;
        case 37: 
          { string.append('\"');
          }
        case 81: break;
        case 44: 
          { return newSymbol(Terminals.THIS,yytext());
          }
        case 82: break;
        case 6: 
          { return newSymbol(Terminals.LPAREN,yytext());
          }
        case 83: break;
        case 1: 
          { throw new Scanner.Exception(yyline + 1, yycolumn + 1, "ERROR ON: '" + yytext() + "'");
          }
        case 84: break;
        case 12: 
          { return newSymbol(Terminals.DIV,yytext());
          }
        case 85: break;
        case 39: 
          { return newSymbol(Terminals.NEW,yytext());
          }
        case 86: break;
        case 8: 
          { return newSymbol(Terminals.MINUS,yytext());
          }
        case 87: break;
        case 17: 
          { return newSymbol(Terminals.RBRACE,yytext());
          }
        case 88: break;
        case 19: 
          { return newSymbol(Terminals.COMMA,yytext());
          }
        case 89: break;
        case 10: 
          { return newSymbol(Terminals.ASSIGN,yytext());
          }
        case 90: break;
        case 43: 
          { return newSymbol(Terminals.BOOLEAN,yytext());
          }
        case 91: break;
        case 20: 
          { return newSymbol(Terminals.DOT,yytext());
          }
        case 92: break;
        case 46: 
          { return newSymbol(Terminals.NULL,yytext());
          }
        case 93: break;
        case 36: 
          { string.append('\n');
          }
        case 94: break;
        case 45: 
          { return newSymbol(Terminals.ELSE,yytext());
          }
        case 95: break;
        case 22: 
          { string.append(yytext());
          }
        case 96: break;
        case 54: 
          { return newSymbol(Terminals.OVERRIDE,yytext());
          }
        case 97: break;
        case 38: 
          { string.append('\b');
          }
        case 98: break;
        case 52: 
          { return newSymbol(Terminals.NATIVE,yytext());
          }
        case 99: break;
        case 3: 
          { return newSymbol(Terminals.ID,yytext());
          }
        case 100: break;
        case 7: 
          { return newSymbol(Terminals.LBRACE,yytext());
          }
        case 101: break;
        case 40: 
          { return newSymbol(Terminals.VAR,yytext());
          }
        case 102: break;
        case 26: 
          { return newSymbol(Terminals.IF,yytext());
          }
        case 103: break;
        case 2: 
          { return newSymbol(Terminals.INTEGER,yytext());
          }
        case 104: break;
        case 50: 
          { return newSymbol(Terminals.CLASS,yytext());
          }
        case 105: break;
        case 14: 
          { return newSymbol(Terminals.NOT,yytext());
          }
        case 106: break;
        case 53: 
          { return newSymbol(Terminals.EXTENDS,yytext());
          }
        case 107: break;
        case 42: 
          { string.setLength(0); yybegin(OTHER_STRING);
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {     return new Symbol(Terminals.EOF, "end-of-file");
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
